name: CI
on:
  [push, pull_request]
jobs:
  generic-build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_image: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, fedora-30, opensuse-leap]
        compiler: [gcc, clang]
    steps:
      - name: Launch Container
        run: |
          #pwd
          ls
          #          DOCKER_IMAGE=${{ matrix.docker_image }} CC=${{ matrix.compiler }} ./.ci/travis.run
      - name: failure
        if: ${{ failure() }}
        run: cat build/test-suite.log || true
