name: CI
on:
  [push, pull_request]
jobs:
  generic-build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_image: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, fedora-30, opensuse-leap]
        compiler: [gcc, clang]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Launch Container
        run: |
          DOCKER_IMAGE=${{ matrix.docker_image }} CC=${{ matrix.compiler }} ./.ci/travis.run
      - name: failure
        if: ${{ failure() }}
        run: cat build/test-suite.log || true
  coverage-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Launch Container
        run: |
          ENABLE_COVERAGE=true DOCKER_IMAGE=ubuntu-18.04 CC=gcc ./.ci/travis.run
      - name: failure
        if: ${{ failure() }}
        run: cat build/test-suite.log || true
  fuzzing-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Launch Container
        run: |
          ENABLE_FUZZING=true DOCKER_IMAGE=fedora-30 CC=clang ./.ci/travis.run
      - name: failure
        if: ${{ failure() }}
        run: cat build/test-suite.log || true
